In [6]:
import requests
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Task 1
# Use the following URL "https://collectionapi.metmuseum.org/public/collection/v1/search?q=QUERY" where "QUERY" is a keyword.
## Suppose your task is to find all artworks related to sunflowers. Perform a search using the word "sunflowers". Carefully examine the response format and save the ids of the obtained objects in the list `sunflower_ids`.

## For your answer, select the ids of the objects (3) that are present in the list: [436524,16822570, 20149, 437329, 2032]

In [7]:
# URL for searching data in the Metropolitan Museum API
url = 'https://collectionapi.metmuseum.org/public/collection/v1/search?q='
IDs = 'sunflowers' # Search keyword ("sunflowers" - sunflowers)
r = requests.get(url+IDs) # Perform a GET request to the API by appending the keyword to the URL
res = r.json() # 'res' now contains the search results in JSON format, which can be analyzed and used further
res

{'total': 96,
 'objectIDs': [436524,
  484935,
  437112,
  210191,
  431264,
  397949,
  656530,
  480725,
  486590,
  375281,
  485308,
  705155,
  700610,
  11922,
  816522,
  343052,
  347980,
  20141,
  2019,
  208554,
  403496,
  360837,
  207869,
  190739,
  437115,
  761604,
  400581,
  423400,
  707887,
  682927,
  57922,
  79739,
  193938,
  649813,
  223828,
  339347,
  437329,
  208218,
  202228,
  437984,
  696949,
  704667,
  822590,
  822589,
  436252,
  436580,
  363282,
  207753,
  437526,
  822570,
  487043,
  203893,
  367434,
  2032,
  423237,
  262423,
  839296,
  367817,
  13644,
  18362,
  820022,
  648617,
  892559,
  761731,
  814626,
  207967,
  626832,
  701016,
  262428,
  262430,
  841928,
  707697,
  205386,
  262378,
  426804,
  436535,
  633526,
  369073,
  747779,
  436121,
  436529,
  852414,
  41480,
  427872,
  895564,
  436144,
  912854,
  436534,
  724844,
  437980,
  631808,
  396836,
  436530,
  834765,
  834580,
  834585]}

In [8]:
sunflower_ids = [] # Creating an empty list to store the found object IDs
# Extracting all object IDs from the search results for the query "sunflowers" and saving them into the list sunflower_ids
# The API response contains the key 'objectIDs', which stores a list of the IDs of the found objects.
sunflower_ids = res['objectIDs']

In [9]:
search_ids = [437329, 20149, 436524, 2032, 16822570]  # List of IDs to check for presence in the sunflower_ids list
for id in search_ids:  # Iterating through each ID in search_ids
    if id in sunflower_ids:  # If the current ID is found in sunflower_ids, print a message indicating the element is found
        print(f"Element {id} found")
    else:  # If the ID is not found, print a message indicating the element is not found
        print(f"Element {id} not found")

Element 437329 found
Element 20149 not found
Element 436524 found
Element 2032 found
Element 16822570 not found

# Task 2
## In the previous step, we obtained search results. The next step is to gather detailed information about these objects.

### Example request to retrieve information about a single object:
The request format is:  
`f'https://collectionapi.metmuseum.org/public/collection/v1/objects/OBJECT_ID'`  
where `OBJECT_ID` is the object's ID.

### Fetch data for object ID 437980. Cross-check the following parameters with their respective values in the response:  
- `artistDisplayName`
- `title`
- `objectID`
- `objectName`
- `department`
- `culture`

In [10]:
# Sending a GET request to the Metropolitan Museum API to retrieve information about the object with ID 437980
r_test = requests.get(f'https://collectionapi.metmuseum.org/public/collection/v1/objects/437980')
obj_test = r_test.json() # Converting the API response from JSON format to a Python dictionary
obj_test # Displaying the result of the request as a dictionary containing information about the specific object

{'objectID': 437980,
 'isHighlight': False,
 'accessionNumber': '49.30',
 'accessionYear': '1949',
 'isPublicDomain': True,
 'primaryImage': 'https://images.metmuseum.org/CRDImages/ep/original/DP130999.jpg',
 'primaryImageSmall': 'https://images.metmuseum.org/CRDImages/ep/web-large/DP130999.jpg',
 'additionalImages': [],
 'constituents': [{'constituentID': 161947,
   'role': 'Artist',
   'name': 'Vincent van Gogh',
   'constituentULAN_URL': 'http://vocab.getty.edu/page/ulan/500115588',
   'constituentWikidata_URL': 'https://www.wikidata.org/wiki/Q5582',
   'gender': ''}],
 'department': 'European Paintings',
 'objectName': 'Painting',
 'title': 'Cypresses',
 'culture': '',
 'period': '',
 'dynasty': '',
 'reign': '',
 'portfolio': '',
 'artistRole': 'Artist',
 'artistPrefix': '',
 'artistDisplayName': 'Vincent van Gogh',
 'artistDisplayBio': 'Dutch, Zundert 1853â€“1890 Auvers-sur-Oise',
 'artistSuffix': '',
 'artistAlphaSort': 'Gogh, Vincent van',
 'artistNationality': 'Dutch',
 'artistBeginDate': '1853',
 'artistEndDate': '1890',
 'artistGender': '',
 'artistWikidata_URL': 'https://www.wikidata.org/wiki/Q5582',
 'artistULAN_URL': 'http://vocab.getty.edu/page/ulan/500115588',
 'objectDate': '1889',
 'objectBeginDate': 1889,
 'objectEndDate': 1889,
 'medium': 'Oil on canvas',
 'dimensions': '36 3/4 x 29 1/8 in. (93.4 x 74 cm)',
 'measurements': [{'elementName': 'Overall',
   'elementDescription': None,
   'elementMeasurements': {'Height': 93.4, 'Width': 74}},
  {'elementName': 'Frame',
   'elementDescription': None,
   'elementMeasurements': {'Depth': 10.795,
    'Height': 116.2052,
    'Width': 96.5202}},
  {'elementName': 'Other',
   'elementDescription': 'glass',
   'elementMeasurements': {'Height': 94.29769, 'Width': 76.517654}}],
 'creditLine': 'Rogers Fund, 1949',
 'geographyType': '',
 'city': '',
 'state': '',
 'county': '',
 'country': '',
 'region': '',
 'subregion': '',
 'locale': '',
 'locus': '',
 'excavation': '',
 'river': '',
 'classification': 'Paintings',
 'rightsAndReproduction': '',
 'linkResource': '',
 'metadataDate': '2024-11-20T04:52:58.38Z',
 'repository': 'Metropolitan Museum of Art, New York, NY',
 'objectURL': 'https://www.metmuseum.org/art/collection/search/437980',
 'tags': [{'term': 'Landscapes',
   'AAT_URL': 'http://vocab.getty.edu/page/aat/300132294',
   'Wikidata_URL': 'https://www.wikidata.org/wiki/Q191163'},
  {'term': 'Cypresses',
   'AAT_URL': 'http://vocab.getty.edu/page/aat/300343641',
   'Wikidata_URL': 'https://www.wikidata.org/wiki/Q146911'}],
 'objectWikidata_URL': 'https://www.wikidata.org/wiki/Q867510',
 'isTimelineWork': True,
 'GalleryNumber': '825'}

In [11]:
# Extracting the required fields
artist_name = obj_test['artistDisplayName']
title = obj_test['title']
object_id = obj_test['objectID']
object_name = obj_test['objectName']
department = obj_test['department']
culture = obj_test['culture']

In [12]:
# Displaying the information
print(f"Artist Name: {artist_name}")
print(f"Title: {title}")
print(f"Object ID: {object_id}")
print(f"Object Name: {object_name}")
print(f"Department: {department}")
print(f"Culture: {culture}")

Artist Name: Vincent van Gogh
Title: Cypresses
Object ID: 437980
Object Name: Painting
Department: European Paintings
Culture:

# Task 3 
## Use a loop to collect information about the objects retrieved in Step 2. Save the results in a DataFrame, including the following parameters:

### objectID â€“ object ID  
### title â€“ title  
### artistDisplayName â€“ author  
### department â€“ department  
### objectBeginDate â€“ start date  
### objectEndDate â€“ end date  
### period â€“ period name  
### objectName â€“ name/category of the object  
### culture â€“ culture  

### How many objects belong to Japanese culture? (culture = Japan)

In [13]:
# Example of a request to retrieve a list of objects related to sunflowers
r = requests.get('https://collectionapi.metmuseum.org/public/collection/v1/search?q=sunflowers')
res = r.json()

In [14]:
# Saving the list of object IDs
sunflower_ids = res.get('objectIDs', [])

In [15]:
# Creating an empty DataFrame for the final data
full_df = pd.DataFrame()

In [16]:
# Loop through all objects in the sunflower_ids list
for i in sunflower_ids:
    # Perform a request for each object
    r_test = requests.get(f'https://collectionapi.metmuseum.org/public/collection/v1/objects/{i}')
    res = r_test.json()
    
    # Extract information about the object using the .get() method for safe value access
    df = pd.DataFrame({
        'objectID': [res.get('objectID')],
        'title': [res.get('title')],
        'artistDisplayName': [res.get('artistDisplayName')],
        'department': [res.get('department')],
        'objectBeginDate': [res.get('objectBeginDate')],
        'objectEndDate': [res.get('objectEndDate')],
        'period': [res.get('period')],
        'objectName': [res.get('objectName')],
        'culture': [res.get('culture')]
    })
    
    # Append the data to the final DataFrame
    full_df = pd.concat([full_df, df], ignore_index=True)

In [17]:
# Print the retrieved data
full_df

,objectID,title,artistDisplayName,department,objectBeginDate,objectEndDate,period,objectName,culture
0,436524,Sunflowers,Vincent van Gogh,European Paintings,1887,1887,,Painting,
1,484935,Sunflowers,Edward McKnight Kauffer,Modern and Contemporary Art,1921,1921,,Painting,
2,437112,Bouquet of Sunflowers,Claude Monet,European Paintings,1881,1881,,Painting,
3,210191,Vase with sunflowers,Rozenburg Plateelfabriek,European Sculpture and Decorative Arts,1896,1896,,Vase,
4,431264,Sunflowers,Lily Converse,Drawings and Prints,1941,1941,,Print,
...,...,...,...,...,...,...,...,...,...
91,396836,The Aesthetic Craze,Currier & Ives,Drawings and Prints,1882,1882,,Print,
92,436530,Oleanders,Vincent van Gogh,European Paintings,1888,1888,,Painting,
93,834765,"A Child's Garden, from ""Picture Poesies""",Arthur Boyd Houghton,Drawings and Prints,1865,1874,,Print,
94,834580,"A Life in a Yearâ€“The Gardenâ€“Noon, from ""Pictur...",Arthur Boyd Houghton,Drawings and Prints,1866,1874,,Print,
95,834585,"A Life in a Yearâ€“The Gardenâ€“Noon, from ""Pictur...",Arthur Boyd Houghton,Drawings and Prints,1866,1874,,Print,

In [18]:
full_df.query('culture == "Japan"') \
    .agg({'objectID': 'count'})

objectID    1
dtype: int64

# Answer: 1 object is related to Japanese culture

# Task 4
## Perform a search query for the department "Asian art" (departmentId = 6) with the tag "cat" and record the object IDs in `cat_ids`. Use the loop from step 4 to retrieve data for the first 1000 objects in the list.

### Answer the following: In which period (`period`) were the most works, represented in the museum, created?

In [19]:
# Sending a request to the Metropolitan Museum API with the search query "cat" in the department with departmentId=6 (e.g., "Asian Art" department)
r = requests.get('https://collectionapi.metmuseum.org/public/collection/v1/search?departmentId=6&q=cat')

# Converting the API response to JSON format
cats = r.json()

# Creating an empty list to store the IDs of objects that match the query
cats_id = []

# Extracting the list of all object IDs found for the query from the 'objectIDs' key
cats_id = cats['objectIDs']

In [20]:
# Limiting the list to the first 1000 objects (to avoid processing an excessively large dataset)
cats_id = cats_id[:1000]

In [21]:
# Creating an empty DataFrame for the final data
full_df_cats_id = pd.DataFrame()

In [22]:
# Looping through all the objects in the list cats_id
for i in cats_id:
    # Sending a request for each object
    r_test = requests.get(f'https://collectionapi.metmuseum.org/public/collection/v1/objects/{i}')
    res = r_test.json()
    
    # Extracting information from the object using .get() for safe access to values
    df = pd.DataFrame({
        'objectID': [res.get('objectID')],  # Object ID
        'title': [res.get('title')],  # Title of the object
        'artistDisplayName': [res.get('artistDisplayName')],  # Artist name
        'department': [res.get('department')],  # Department name
        'objectBeginDate': [res.get('objectBeginDate')],  # Start date of the object
        'objectEndDate': [res.get('objectEndDate')],  # End date of the object
        'period': [res.get('period')],  # Period of the object
        'objectName': [res.get('objectName')],  # Name/category of the object
        'culture': [res.get('culture')]  # Culture of the object
    })
    
    # Concatenating the current df with the final DataFrame
    full_df_cats_id = pd.concat([full_df_cats_id, df], ignore_index=True)

In [23]:
# Print the obtained data
full_df_cats_id

,objectID,title,artistDisplayName,department,objectBeginDate,objectEndDate,period,objectName,culture
0,49698,Cat,Zhang Yuguang,Asian Art,1900,1968,,Folding fan mounted as an album leaf,China
1,49470,Cat,Wang Li,Asian Art,1813,1879,Qing dynasty (1644â€“1911),Hanging scroll,China
2,36221,Cat,Wang Yun,Asian Art,1900,1933,,Hanging scroll,China
3,53222,Musk Cat,Uto Gyoshi,Asian Art,1550,1599,Muromachi period (1392â€“1573),Hanging scroll,Japan
4,60873,Head ornament,,Asian Art,960,1279,Song dynasty (960â€“1279) or later,Head ornament,China
...,...,...,...,...,...,...,...,...,...
995,63003,Bowl,,Asian Art,1840,1840,Edo period (1615â€“1868),Bowl,Japan
996,63006,Bowl,,Asian Art,1830,1830,Edo period (1615â€“1868),Bowl,Japan
997,62993,Cup,,Asian Art,1780,1780,Edo period (1615â€“1868),Cup,Japan
998,62933,Bowl,,Asian Art,1750,1750,Edo period (1615â€“1868),Bowl,Japan
999,62938,Dish in the Shape of a Princess,,Asian Art,1690,1799,Edo period (1615â€“1868),Plate,Japan

In [24]:
# Count in which period (period) the largest number of works was created, represented in the museum
full_df_cats_id.period.value_counts()

period
Edo period (1615â€“1868)                                         313
                                                               147
Qing dynasty (1644â€“1911)                                        60
Ming dynasty (1368â€“1644)                                        44
Muromachi period (1392â€“1573)                                    28
                                                              ...
Ming dynasty (1368â€“1644), Wanli period (1573â€“1620)               1
Ming dynasty (1368â€“1644), Chongzhen period (1628â€“44)             1
Ming Dynasty (1368â€“1644)                                         1
Song dynasty (960â€“1279)                                          1
Muromachi period (1392â€“1573) or Momoyama period (1573â€“1615)      1
Name: count, Length: 126, dtype: int64

# Answear: Edo period (1615 - 1868)